version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telecomdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  etl:
    build: ./etl
    depends_on:
      - db
    volumes:
      - ./data:/data

  webapp:
    build: ./webapp
    ports:
      - "5000:5000"
    depends_on:
      - db

